name:                diagrams
version:             0.1.0.0
github:              "githubuser/diagrams"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/diagrams#readme>

dependencies:
- base >= 4.7 && < 5
- diagrams-lib
- diagrams-contrib
- diagrams-svg
- diagrams-core
- containers
- diagrams-builder
- diagrams-pgf
- time
- lens
- SVGFonts
- algebraic-graphs
- data-default-class
- split
- texrunner
# - turtle
# - random


library:
  source-dirs: src

executables:
  diagrams-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - diagrams
    

tests:
  diagrams-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - diagrams

default-extensions:
- TypeFamilies
- FlexibleContexts
- NoMonomorphismRestriction